FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    curl \
    wget \
    sudo \
    iproute2 \
    procps \
    nano \
    python3 \
    util-linux \
    tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

CMD ["tail", "-f", "/dev/null"]
